function [Y_est,Y_est_sub] = sim_model_clstr(theta,trm_chsn_lin,trm_chsn_lin_org,U_delay_mat,n_lin_trms,y_lag_lin_srt,nl_ord,trm_chsn_nl,bias,mod_sub_cmp)
%SIM_MODEL_CLSTR Evaluate a polynomial input-only model and a term subset.
%   This low-level helper reconstructs the selected linear and nonlinear
%   regressors from the delayed-input matrix, evaluates the complete model,
%   and separately evaluates a requested subcomponent. It is used to isolate
%   the canonical PAC term clusters described in equation (17) of the paper.
%   Inputs
%   ------
%   theta             : Coefficient vector of the identified model.
%   trm_chsn_lin      : Indices of selected linear regressors.
%   trm_chsn_lin_org  : Linear regressors used to generate nonlinear terms.
%   U_delay_mat       : Superset matrix of delayed input regressors.
%   n_lin_trms        : Number of candidate linear regressors.
%   y_lag_lin_srt     : Retained compatibility argument; output lags are not
%                       used by the present input-only PAC implementation.
%   nl_ord            : Maximum polynomial degree.
%   trm_chsn_nl       : Indices of selected nonlinear regressors.
%   bias              : Identified constant/bias term.
%   mod_sub_cmp       : Logical/numeric selector over the assembled final
%                       model terms for the requested subcomponent.
%   Outputs
%   -------
%   Y_est             : Complete model response.
%   Y_est_sub         : Response generated by the selected term subset only.

%% Determine simulation length and construct candidate regressors

% Assemble and simulate the polynomial input-only model.
% Existing inline notes below describe the NonSysID-i indexing conventions.
% trm_chsn_lin - term indecies of chosen linear terms from the superset of terms
% max_dyn_ord - maximum dynamic order of the original superset of terms 
% U_delay_mat - Matrix containing all the linear input lagged terms (superset)
% mod_sub_cmp - Sub-component of the model to be extracted

size_U_d_m = size(U_delay_mat);
dat_len = size_U_d_m(1);

[unq_nl_comb] = nl_term_comb(nl_ord,n_lin_trms); % Evalutate nonlinear combinations 
nl_terms = sum([unq_nl_comb{2:end,2}]); % Total no. of nonlinear terms
X_nl = zeros(dat_len,nl_terms);

X_sup_lin = U_delay_mat;

X_sub_lin = X_sup_lin(:,trm_chsn_lin); % Linear subset of terms 
X_sub_lin_org = X_sup_lin(:,trm_chsn_lin_org); % Initial linear subset of terms 
% ---------- Nonlinear regressors are formed from X_sub_lin -----------
if nl_ord >= 2
    nl_ind_end = 0;
    for n = 2:nl_ord
        unq_comb = unq_nl_comb{(n),1};
        [X_comp] = nl_reg_data_mat(X_sub_lin_org,unq_comb);
        
        nl_ind = nl_ind_end + unq_nl_comb{(n),2};
        
        X_nl(:,nl_ind_end+1:nl_ind) = X_comp;
        
        nl_ind_end = nl_ind ; 
    end
    
    X_main_sup = [X_sub_lin_org , X_nl];
    X_main = [X_sub_lin , X_main_sup(:,trm_chsn_nl)];
else
    X_main = X_sub_lin;           
end
% ---------------------------------------------------------------------

%% Evaluate the complete model and selected subcomponent
mod_sub_cmp = logical(mod_sub_cmp);

if isempty(X_main)
    Y_est = bias.*ones(dat_len,1); % Simulate model
    Y_est_sub = zeros(dat_len,1); % Simulation of just the extracted sub-component of the model
else
    Y_est = X_main*theta + bias.*ones(dat_len,1); % Simulate model
    Y_est_sub = X_main(:,mod_sub_cmp)*theta(mod_sub_cmp); % Simulate model sub-component
end

end
